spring:
  datasource:
    url:
    username:
    password:
  messages:
    basename:
  session:
    store-type:
  redis:
    session:
      host:
      password:
      port:
logging:
  level:
    org:
      springframework:
        jdbc: debug
    com:
      airjnc: trace
cloud:
  naver:
    credentials:
      accessKey:
      secretKey:
    mail:
      templateSid:
        resetPassword:
      uri:
        send:

