spring:
  datasource:
    url:
    username:
    password:
  messages:
    basename:
  session:
    store-type:
  redis:
    session:
      host:
      password:
      port:
logging:
  level:
    org:
      springframework:
        jdbc:
cloud:
  naver:
    credentials:
      accessKey:
      secretKey:
    mailer:
      resetPasswordTemplateSid:
