#!/bin/bash
docker pull hanjn2842/airjnc:latest
docker ps -f name=app -aq | xargs -r docker container stop
docker ps -f name=app -aq | xargs -r docker container rm
docker run -p 80:8080 --name app -d hanjn2842/airjnc:latest
