#!/bin/bash
docker pull hanjn2842/airjnc:latest
docker ps -f name=app -aq | xargs -r docker container stop
docker ps -f name=app -aq | xargs -r docker container rm
docker run -p 8080:80 --name app -d hanjn2842/airjnc:latest
